name             'osl-imap'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
chef_version     '>= 16.0'
issues_url       'https://github.com/osuosl-cookbooks/osl-imap/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-imap'
description      'Installs/Configures osl-imap'
version          '3.0.1'

supports         'almalinux', '~> 8.0'
supports         'almalinux', '~> 9.0'
supports         'almalinux', '~> 10.0'

depends          'certificate'
depends          'osl-acme'
depends          'osl-apache'
depends          'osl-firewall'
